# Site settings
title: HB ☺ 
description: Notes，Posts，Microblog，HbW.Me 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://hellopages.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
  notes:
    output: true
  microblog:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
      categories: "notes"
  - scope:
      path: ""
      type: "microblog"
    values:
      layout: "post"
      categories: "microblog"

# Pagination settings
pagination:
  enabled: true
  paginate: 3
  paginate_path: "/page/:num/"
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
# ai bug notes,文章同步 posts，posts同步MB
  collections:
  blog:
    output: true
    output_dir: blog  # 输出到 _site/blog 目录
  note:
    output: true
    output_dir: note  # 输出到 _site/note 目录

    
# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2
  # jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
