# Site settings
title: My Digital Garden
description: A place for my thoughts, notes, and ideas
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
  notes:
    output: true
  microblog:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "post"
      categories: "notes"
  - scope:
      path: ""
      type: "microblog"
    values:
      layout: "post"
      categories: "microblog"

# Pagination settings
paginate: 10
paginate_path: "/page/:num/"

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
